site_name: SthaliDB
site_url: https://{{cookiecutter.github_username}}.github.io/{{cookiecutter.project_name}}/
site_description: "{{cookiecutter.project_short_description}}"
site_author: "{{cookiecutter.full_name}}"
repo_url: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.project_name}}/
repo_name: {{cookiecutter.project_name}}
nav:
  - Home: index.md
  - Requirements: requirements.md
  - Installation: installation.md
  # - Usage: usage.md
  - API Reference: /api/*.md
    # - Clients: clients.md
    # - Dependencies: dependencies.md
  - About:
    - License: https://raw.githubusercontent.com/{{cookiecutter.github_username}}/{{cookiecutter.project_name}}/main/LICENSE
    - Release Notes: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.project_name}}/pulls?q=is%3Apr+is%3Aclosed+release
    - Issue Tracker: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.project_name}}/issues
theme: readthedocs
